// Placeholder exports - not used in polygon system
export * from './rocket'
export * from './arrow'
export * from './boat'
export * from './candle'
export * from './cat'
export * from './diamond'
export * from './fish'
export * from './flyingBird'
export * from './house'
export * from './parallelogramShape'
export * from './rabbit'
export * from './rectangle'
export * from './runner'
export * from './swan'
export * from './triangle'
export * from './windmill'
